import React,{useEffect,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import{UploadCloud,ShieldCheck,HelpCircle,Download,Minus,Plus,Maximize2,ChevronLeft,ChevronRight,X,RotateCcw,Sparkles}from'lucide-react';
import{jsPDF}from'jspdf';
import html2canvas from'html2canvas';
import'./styles.css';
import'./auto-detect.css';
type PDFDocumentProxy=any;
type Kind='image'|'pdf'|'web'; type Format='jpg'|'png'|'pdf'|'webp';
const SAMPLE='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="760"><rect width="1200" height="760" fill="#f7fafb"/><rect x="0" y="0" width="1200" height="92" fill="#0c4f68"/><text x="62" y="58" fill="white" font-size="30" font-family="Arial">DOCUMENT PREVIEW</text><circle cx="1060" cy="355" r="185" fill="#dcecf0"/><rect x="735" y="245" width="360" height="310" rx="18" fill="#176c83"/><rect x="780" y="300" width="270" height="18" rx="9" fill="#cce7ea"/><rect x="780" y="345" width="210" height="18" rx="9" fill="#cce7ea"/><rect x="780" y="390" width="245" height="18" rx="9" fill="#cce7ea"/><text x="70" y="245" fill="#102d3a" font-size="58" font-weight="bold" font-family="Arial">让每一份文件</text><text x="70" y="315" fill="#102d3a" font-size="58" font-weight="bold" font-family="Arial">都有清晰归属</text><text x="72" y="380" fill="#617580" font-size="24" font-family="Arial">上传文件后，所有调整都会立即出现在这里</text><rect x="72" y="460" width="520" height="16" rx="8" fill="#d6e0e3"/><rect x="72" y="500" width="450" height="16" rx="8" fill="#d6e0e3"/><rect x="72" y="540" width="490" height="16" rx="8" fill="#d6e0e3"/><rect y="690" width="1200" height="70" fill="#e7f0f2"/></svg>`);

function App(){
 const[kind,setKind]=useState<Kind>('image'),[src,setSrc]=useState(SAMPLE),[name,setName]=useState('示例预览'),[text,setText]=useState('版权所有'),[angle,setAngle]=useState(32),[density,setDensity]=useState(64),[opacity,setOpacity]=useState(24),[size,setSize]=useState(24),[color,setColor]=useState('#333333'),[format,setFormat]=useState<Format>('jpg'),[zoom,setZoom]=useState(72),[pdf,setPdf]=useState<PDFDocumentProxy|null>(null),[page,setPage]=useState(1),[busy,setBusy]=useState(false),[drag,setDrag]=useState(false),[url,setUrl]=useState(''),[error,setError]=useState('');
 const canvas=useRef<HTMLCanvasElement>(null),stage=useRef<HTMLDivElement>(null),input=useRef<HTMLInputElement>(null);
 const detectFile=(f:File):{kind:Kind;format:Format}=>{const ext=f.name.split('.').pop()?.toLowerCase();if(f.type==='application/pdf'||ext==='pdf')return{kind:'pdf',format:'pdf'};if(f.type==='text/html'||ext==='html'||ext==='htm')return{kind:'web',format:'png'};if(f.type==='image/png'||ext==='png')return{kind:'image',format:'png'};if(f.type==='image/webp'||ext==='webp')return{kind:'image',format:'webp'};return{kind:'image',format:'jpg'}};
 const drawWatermark=(ctx:CanvasRenderingContext2D,w:number,h:number)=>{const scale=w/900,font=Math.max(14,size*scale),tile=document.createElement('canvas'),tw=Math.max(font*6,w*(1.05-density/120)),th=Math.max(font*3,h*(.72-density/180));tile.width=tw;tile.height=th;const t=tile.getContext('2d')!;t.translate(tw/2,th/2);t.rotate(angle*Math.PI/180);t.globalAlpha=opacity/100;t.fillStyle=color;t.font=`600 ${font}px "Microsoft YaHei",sans-serif`;t.textAlign='center';t.textBaseline='middle';t.fillText(text||' ',0,0);ctx.save();ctx.fillStyle=ctx.createPattern(tile,'repeat')!;ctx.fillRect(0,0,w,h);ctx.restore()};
 const render=async()=>{const c=canvas.current;if(!c)return;const ctx=c.getContext('2d')!;if(kind==='web'&&url){return}const img=new Image();img.onload=()=>{c.width=img.naturalWidth;c.height=img.naturalHeight;ctx.clearRect(0,0,c.width,c.height);ctx.drawImage(img,0,0);drawWatermark(ctx,c.width,c.height)};img.src=src};
 useEffect(()=>{render()},[src,text,angle,density,opacity,size,color,kind,url]);
 const loadPdfPage=async(doc:PDFDocumentProxy,n:number)=>{const p=await doc.getPage(n),v=p.getViewport({scale:1.8}),off=document.createElement('canvas');off.width=Math.ceil(v.width);off.height=Math.ceil(v.height);await p.render({canvas:off,canvasContext:off.getContext('2d')!,viewport:v}).promise;setSrc(off.toDataURL('image/png'))};
 const renderPdfCanvas=async(doc:PDFDocumentProxy,n:number)=>{const p=await doc.getPage(n),v=p.getViewport({scale:1.8}),out=document.createElement('canvas');out.width=Math.ceil(v.width);out.height=Math.ceil(v.height);await p.render({canvas:out,canvasContext:out.getContext('2d')!,viewport:v}).promise;drawWatermark(out.getContext('2d')!,out.width,out.height);return out};
 useEffect(()=>{if(!pdf)return;let live=true;setBusy(true);setError('');loadPdfPage(pdf,page).catch(()=>live&&setError('PDF 页面读取失败，请确认文件未加密或损坏')).finally(()=>live&&setBusy(false));return()=>{live=false}},[page,pdf]);
 const handleFile=async(f?:File)=>{if(!f)return;setBusy(true);setError('');const detected=detectFile(f);setKind(detected.kind);setFormat(detected.format);setName(f.name);setPdf(null);setPage(1);setUrl('');try{if(detected.kind==='pdf'){const pdfjs=await import('pdfjs-dist'),worker=await import('pdfjs-dist/build/pdf.worker.min.mjs?url');pdfjs.GlobalWorkerOptions.workerSrc=worker.default;const d=await pdfjs.getDocument({data:new Uint8Array(await f.arrayBuffer())}).promise;setPdf(d)}else if(detected.kind==='web'){setUrl(URL.createObjectURL(f));setBusy(false)}else{setSrc(URL.createObjectURL(f));setBusy(false)}}catch(e){setBusy(false);setError('文件读取失败，请确认文件格式正确后重试')}};
 useEffect(()=>{const paste=(e:ClipboardEvent)=>{const f=[...(e.clipboardData?.files||[])][0];if(f)handleFile(f)};window.addEventListener('paste',paste);return()=>window.removeEventListener('paste',paste)},[]);
 const clear=()=>{setKind('image');setFormat('jpg');setName('示例预览');setSrc(SAMPLE);setPdf(null);setPage(1);setUrl('')};
 const exportFile=async()=>{setBusy(true);try{if(format==='pdf'&&pdf){let doc:jsPDF|null=null;for(let n=1;n<=pdf.numPages;n++){const out=await renderPdfCanvas(pdf,n),orient=out.width>out.height?'landscape':'portrait';if(!doc)doc=new jsPDF({orientation:orient,unit:'px',format:[out.width,out.height]});else doc.addPage([out.width,out.height],orient);doc.addImage(out.toDataURL('image/jpeg',.94),'JPEG',0,0,out.width,out.height)}doc?.save('watermarked.pdf');return}let out:HTMLCanvasElement;if(kind==='web'&&url){out=await html2canvas(stage.current!,{backgroundColor:'#fff',useCORS:true,scale:2})}else out=canvas.current!;if(format==='pdf'){const orient=out.width>out.height?'landscape':'portrait',doc=new jsPDF({orientation:orient,unit:'px',format:[out.width,out.height]});doc.addImage(out.toDataURL('image/jpeg',.94),'JPEG',0,0,out.width,out.height);doc.save('watermarked.pdf')}else{const mime=format==='jpg'?'image/jpeg':`image/${format}`,a=document.createElement('a');a.download=`watermarked.${format}`;a.href=out.toDataURL(mime,.94);a.click()}}catch(e){alert('导出失败，请检查文件后重试。网页受限制时，可改用网页截图上传。')}finally{setBusy(false)}};
 return <div className="app"><header><div className="brand"><span className="drop">水</span><b>水印一下</b></div><div className="headRight"><span><ShieldCheck/>文件仅在你的浏览器中处理</span><button onClick={()=>alert('上传文件后，调整任意参数即可实时预览，无需点击应用。')}><HelpCircle/>帮助</button></div></header>
 <main><aside><div className="autoDetect"><Sparkles/><div><strong>自动识别格式</strong><span>无需预先选择文件类型</span></div></div>
 <div className={'dropzone '+(drag?'drag':'')} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);handleFile(e.dataTransfer.files[0])}} onClick={()=>input.current?.click()}><UploadCloud/><strong>{busy?'正在读取…':'上传文件'}</strong><span>点击、拖到这里，或直接粘贴</span><em>支持 JPG、PNG、WebP、PDF、HTML</em></div>
 <input ref={input} hidden type="file" accept="image/*,.pdf,application/pdf,.html,.htm,text/html" onChange={e=>{handleFile(e.target.files?.[0]);e.currentTarget.value=''}}/>{error&&<div className="fileError">{error}</div>}
 <div className="controls"><label>水印文字<input value={text} onChange={e=>setText(e.target.value)} maxLength={40}/></label><Range label="角度" value={angle} min={-90} max={90} suffix="°" set={setAngle}/><Range label="密度" value={density} min={10} max={90} suffix="%" set={setDensity}/><Range label="透明度" value={opacity} min={5} max={90} suffix="%" set={setOpacity}/><Range label="字号" value={size} min={12} max={64} suffix="px" set={setSize}/><label className="color">颜色<div><input type="color" value={color} onChange={e=>setColor(e.target.value)}/><span>{color.toUpperCase()}</span></div></label></div></aside>
 <section className="workspace"><div className="filebar"><div><span className="status"></span><b>{name}</b></div>{name!=='示例预览'&&<button onClick={clear}><X/>移除</button>}</div><div className="viewport"><div ref={stage} className="stage" style={{transform:`scale(${zoom/100})`}}>{kind==='web'&&url?<><iframe src={url}/><div className="webmarks" style={{'--wm':`url("data:image/svg+xml,${encodeURIComponent(`<svg xmlns='http://www.w3.org/2000/svg' width='300' height='180'><text x='150' y='90' text-anchor='middle' fill='${color}' fill-opacity='${opacity/100}' font-size='${size}' font-family='Arial' transform='rotate(${angle} 150 90)'>${text}</text></svg>`)}")` } as any}/></>:<canvas ref={canvas}/>}</div></div><div className="canvasbar"><div className="pager"><button disabled={!pdf||page<=1} onClick={()=>setPage(page-1)}><ChevronLeft/></button><span>{page} / {pdf?.numPages||1}</span><button disabled={!pdf||page>=pdf.numPages} onClick={()=>setPage(page+1)}><ChevronRight/></button></div><div className="zoomer"><button onClick={()=>setZoom(Math.max(30,zoom-10))}><Minus/></button><span>{zoom}%</span><button onClick={()=>setZoom(Math.min(140,zoom+10))}><Plus/></button><button onClick={()=>setZoom(72)} title="重置"><RotateCcw/></button><button onClick={()=>setZoom(100)} title="实际大小"><Maximize2/></button></div></div></section></main>
 <footer><div className="formats"><strong>导出格式</strong>{(['jpg','png','pdf','webp']as Format[]).map(f=><button className={format===f?'selected':''} onClick={()=>setFormat(f)} key={f}>{f.toUpperCase()}</button>)}</div><button className="download" onClick={exportFile} disabled={busy}><Download/>{busy?'处理中…':'下载'}</button></footer></div>}
function Range({label,value,min,max,suffix,set}:any){return <label className="range"><span>{label}<output>{value}{suffix}</output></span><input type="range" value={value} min={min} max={max} onChange={e=>set(+e.target.value)}/></label>}
createRoot(document.getElementById('root')!).render(<App/>);
